name: CI - check and prepare

on:
  push:
    branches: [ main ]

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Try to build Docker image
        run: docker build --tag bot .

      - name: Delete image
        run: docker image rm bot

  code_check:
    runs-on: ubuntu-latest
    steps:
      - name: Python Linter
        uses: sunnysid3up/python-linter@master
        with:
          pylint-options: "--max-line-length=120"