name: CI - check and prepare

on:
  push:
    branches: [ main ]

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Try to build Docker image
        run: docker build --tag bot .

      - name: Delete image
        run: docker image rm bot

  code_check:
    runs-on: ubuntu-latest
    steps:
      - name: Where am i
        run: ls
      - name: Python Linter
        uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "main helpers"
          use-pylint: true
          use-pycodestyle: false
          use-flake8: false
          use-black: false
          use-mypy: false
          use-isort: false
          extra-pylint-options: "--max-line-length=120"