name: CI - check and prepare

on:
  push:
    branches: [ main ]

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Try to build Docker image
        run: docker build --tag bot .

      - name: Delete image
        run: docker image rm bot