name: CI - check and prepare

on:
  push:
    branches: [ main ]

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Run linter
        uses: py-actions/flake8@v2
        with:
          max-line-length: "120"
          path: "main.py"