name: Check

on:
  push:
    branches: [ main ]

jobs:
  run_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Run linter
        uses: ricardochaves/python-lint@v1.4.0
          with:
            python-root-list: "main.py helpers.py"
            use-pylint: true
            use-pycodestyle: false
            use-flake8: false
            use-black: false
            use-mypy: false
            use-isort: false
            extra-pylint-options: "--max-line-length=120"

